import User from "../models/User.js";
import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";

// Generate JWT token
const generateToken = (id) => {
    return jwt.sign({ id }, process.env.JWT_SECRET, { expiresIn: "30d" });
};

// Register user
export const register = async (req, res) => {
    try {
        const { name, email, password } = req.body;
        // if user press the registered button without entering name email password then all fields are required message pop ups.
        if (!name || !email || !password) return res.status(400).json({ success: false, message: "All fields are required" });

        // Check if user exists
        const existingUser = await User.findOne({ email });
        // if user present with given email then it will pop up with meassage that is User already exists
        if (existingUser) return res.status(400).json({ success: false, message: "User already exists" });
        
        // if existed user is not present in our database then we firstly provide him to choose a hash password using bicrypt library and then we create that user in our database.
        // Hash password
        const hashedPassword = await bcrypt.hash(password, await bcrypt.genSalt(10));

        // Create user
        const user = await User.create({ name, email, password: hashedPassword });

        //generating a token and this token will send in response to user after succesfull creation in database
        // this _id is autogenerated in mongodb
        const token = generateToken(user._id);

        res.status(201).json({ success: true, token, user });
    } catch (error) {
        console.error("Register error:", error.message);
        res.status(500).json({ success: false, message: "Server error" });
    }
};

// Login user
export const login = async (req, res) => {
    try { 
        // here we want only email and password to login not name
        const { email, password } = req.body;

        if (!email || !password) return res.status(400).json({ success: false, message: "All fields are required" });

        // Find user
        const user = await User.findOne({ email });
        if (!user) return res.status(400).json({ success: false, message: "Invalid credentials" });

        // Check password
        const isMatch = await bcrypt.compare(password, user.password);
        if (!isMatch) {
            return res.status(400).json({ success: false, message: "Invalid credentials" });
        }

        const token = generateToken(user._id);

        res.status(201).json({ success: true, token, user });
    } catch (error) {
        console.error("Register error:", error.message);
        res.status(500).json({ success: false, message: "Server error" });
    }
};

// Get current user
export const getUser = async (req, res) => {
    try {
        const user = await User.findById(req.userId).select("-password");
        if (!user) {
            return res.status(400).json({ success: false, message: "User not found" });
        }

        res.json({ success: true, user });
    } catch (error) {
        console.error("Get user error:", error.message);
        res.status(500).json({ success: false, message: "Server error" });
    }
};

// login authentication completed
